### ISSUE TITLE
More private channel commands

### ISSUE THREAD

**Issue by RandommUser** [hivehelsinki/discord-student#15]
/leavegroup command
Kick yourself out of a private channel

/removemember command
Ability to remove member(s) from your private channels.

With the current permissions on the test server these are not needed since you have the manage channel permission, but that will change after official launch

**Comment by forbidden-arts** [comment]
Is there any progress on this? The manage channel permission is no longer applied to the user creating the group. Managing users (particularly for rotating membership groups like Hexagon) is becoming untenable.

**Comment by alcjzk** [comment]
I can look into implementing this behaviour some time in the near future :)
